spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/courseinfo?serverTimezone=GMT%2B8
    username: root
    password: 52582320797lml
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.springboot.mybatis.springbootmybatisdemo2.model
  mapper-locations: classpath:mapper/*.xml
#